Convert htgettoken function header comments into docstrings
fermitools/htgettoken pull request #62
Opened 2023-01-03 14:10 UTC by duncanmmacleod

This PR converts the comments that come before most (all?) functions into docstrings for the functions.

2023-01-03 16:48 UTC, DrDaveD commented
This one needs rebasing too.

2023-01-03 18:35 UTC, DrDaveD requested changes

2023-02-12 00:40 UTC, duncanmmacleod commented on htgettoken.py
> +
Sorry for the delay, this was just addressed.

2023-02-13 20:19 UTC, DrDaveD approved these changes

2023-02-13 20:20 UTC, merged